# coding: utf-8

# flake8: noqa

"""
    Speech Services API v2.0

    Speech Services API v2.0.  # noqa: E501

    OpenAPI spec version: v2.0
    Contact: crservice@microsoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from cris_client.api.custom_speech_subscriptions_management_api import CustomSpeechSubscriptionsManagementApi
from cris_client.api.custom_speech_accuracy_tests_api import CustomSpeechAccuracyTestsApi
from cris_client.api.custom_speech_datasets_for_model_adaptation_api import CustomSpeechDatasetsForModelAdaptationApi
from cris_client.api.custom_speech_endpoints_api import CustomSpeechEndpointsApi
from cris_client.api.custom_speech_models_api import CustomSpeechModelsApi
from cris_client.api.custom_speech_transcriptions_api import CustomSpeechTranscriptionsApi
from cris_client.api.language_generation_endpoints_api import LanguageGenerationEndpointsApi
from cris_client.api.language_generation_models_api import LanguageGenerationModelsApi
from cris_client.api.service_health_api import ServiceHealthApi
from cris_client.api.voice_datasets_api import VoiceDatasetsApi
from cris_client.api.voice_endpoints_api import VoiceEndpointsApi
from cris_client.api.voice_models_api import VoiceModelsApi
from cris_client.api.voice_tests_api import VoiceTestsApi

# import ApiClient
from cris_client.api_client import ApiClient
from cris_client.configuration import Configuration
# import models into sdk package
from cris_client.models.component import Component
from cris_client.models.dataset import Dataset
from cris_client.models.dataset_definition import DatasetDefinition
from cris_client.models.dataset_identity import DatasetIdentity
from cris_client.models.dataset_update import DatasetUpdate
from cris_client.models.endpoint import Endpoint
from cris_client.models.endpoint_data import EndpointData
from cris_client.models.endpoint_data_definition import EndpointDataDefinition
from cris_client.models.endpoint_definition import EndpointDefinition
from cris_client.models.endpoint_update import EndpointUpdate
from cris_client.models.error_content import ErrorContent
from cris_client.models.error_detail import ErrorDetail
from cris_client.models.health_status_response import HealthStatusResponse
from cris_client.models.i_read_only_dictionary2 import IReadOnlyDictionary2
from cris_client.models.i_read_only_dictionary21 import IReadOnlyDictionary21
from cris_client.models.inner_error import InnerError
from cris_client.models.model import Model
from cris_client.models.model_definition import ModelDefinition
from cris_client.models.model_identity import ModelIdentity
from cris_client.models.model_update import ModelUpdate
from cris_client.models.move_to_subscription_definition import MoveToSubscriptionDefinition
from cris_client.models.speech_endpoint_definition import SpeechEndpointDefinition
from cris_client.models.speech_model_definition import SpeechModelDefinition
from cris_client.models.test import Test
from cris_client.models.test_definition import TestDefinition
from cris_client.models.test_update import TestUpdate
from cris_client.models.transcription import Transcription
from cris_client.models.transcription_definition import TranscriptionDefinition
from cris_client.models.transcription_update import TranscriptionUpdate
from cris_client.models.voice_test import VoiceTest
from cris_client.models.voice_test_definition import VoiceTestDefinition
from cris_client.models.web_hook_configuration_secret import WebHookConfigurationSecret
from cris_client.models.web_hook_update import WebHookUpdate
