# coding: utf-8

"""
    Speech Services API v2.0

    Speech Services API v2.0.  # noqa: E501

    OpenAPI spec version: v2.0
    Contact: crservice@microsoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.voice_tests_api import VoiceTestsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestVoiceTestsApi(unittest.TestCase):
    """VoiceTestsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.voice_tests_api.VoiceTestsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_voice_test(self):
        """Test case for create_voice_test

        Creates a new voice test.  # noqa: E501
        """
        pass

    def test_delete_voice_test(self):
        """Test case for delete_voice_test

        Deletes the specified voice test.  # noqa: E501
        """
        pass

    def test_get_voice_test(self):
        """Test case for get_voice_test

        Gets detail of the specified voice test.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
