# coding: utf-8

"""
    Speech Services API v2.0

    Speech Services API v2.0.  # noqa: E501

    OpenAPI spec version: v2.0
    Contact: crservice@microsoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.voice_models_api import VoiceModelsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestVoiceModelsApi(unittest.TestCase):
    """VoiceModelsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.voice_models_api.VoiceModelsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_voice_model(self):
        """Test case for create_voice_model

        Creates a new voice model object.  # noqa: E501
        """
        pass

    def test_delete_voice_model(self):
        """Test case for delete_voice_model

        Deletes the voice model with the given id.  # noqa: E501
        """
        pass

    def test_get_supported_locales_for_voice_models(self):
        """Test case for get_supported_locales_for_voice_models

        Gets a list of supported locales for custom voice Models.  # noqa: E501
        """
        pass

    def test_get_voice_model(self):
        """Test case for get_voice_model

        Gets specified voice model details.  # noqa: E501
        """
        pass

    def test_get_voice_models(self):
        """Test case for get_voice_models

        Gets a list of voice model details.  # noqa: E501
        """
        pass

    def test_update_voice_model(self):
        """Test case for update_voice_model

        Updates the metadata of the voice model identified by the given ID.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
