# coding: utf-8

"""
    Speech Services API v2.0

    Speech Services API v2.0.  # noqa: E501

    OpenAPI spec version: v2.0
    Contact: crservice@microsoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.voice_test_definition import VoiceTestDefinition  # noqa: E501
from swagger_client.rest import ApiException


class TestVoiceTestDefinition(unittest.TestCase):
    """VoiceTestDefinition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVoiceTestDefinition(self):
        """Test VoiceTestDefinition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.voice_test_definition.VoiceTestDefinition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
