# coding: utf-8

"""
    Speech Services API v2.0

    Speech Services API v2.0.  # noqa: E501

    OpenAPI spec version: v2.0
    Contact: crservice@microsoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.custom_speech_subscriptions_management_api import CustomSpeechSubscriptionsManagementApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCustomSpeechSubscriptionsManagementApi(unittest.TestCase):
    """CustomSpeechSubscriptionsManagementApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.custom_speech_subscriptions_management_api.CustomSpeechSubscriptionsManagementApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_post_move_to_subscription(self):
        """Test case for post_move_to_subscription

        Initiates a task that moves all entities associated with the authenticated subscription to another one.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
