# coding: utf-8

"""
    Speech Services API v2.0

    Speech Services API v2.0.  # noqa: E501

    OpenAPI spec version: v2.0
    Contact: crservice@microsoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.language_generation_endpoints_api import LanguageGenerationEndpointsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLanguageGenerationEndpointsApi(unittest.TestCase):
    """LanguageGenerationEndpointsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.language_generation_endpoints_api.LanguageGenerationEndpointsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_language_generation_endpoint(self):
        """Test case for create_language_generation_endpoint

        Creates a new language generation endpoint.  # noqa: E501
        """
        pass

    def test_delete_language_generation_endpoint(self):
        """Test case for delete_language_generation_endpoint

        Deletes the language generation model endpoint with the given id.  # noqa: E501
        """
        pass

    def test_get_language_generation_endpoint(self):
        """Test case for get_language_generation_endpoint

        Gets the specified deployed language generation endpoint.  # noqa: E501
        """
        pass

    def test_get_language_generation_endpoints(self):
        """Test case for get_language_generation_endpoints

        Gets all language generation endpoint of a subscription.  # noqa: E501
        """
        pass

    def test_get_supported_locales_for_language_generation_endpoints(self):
        """Test case for get_supported_locales_for_language_generation_endpoints

        Gets a list of supported locales for language generation endpoint creation.  # noqa: E501
        """
        pass

    def test_update_language_generation_endpoint(self):
        """Test case for update_language_generation_endpoint

        Updates the mutable details of the language generation endpoint identified by its id.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
