# coding: utf-8

"""
    Speech Services API v2.0

    Speech Services API v2.0.  # noqa: E501

    OpenAPI spec version: v2.0
    Contact: crservice@microsoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.model_definition import ModelDefinition  # noqa: E501
from swagger_client.rest import ApiException


class TestModelDefinition(unittest.TestCase):
    """ModelDefinition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelDefinition(self):
        """Test ModelDefinition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.model_definition.ModelDefinition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
